# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      #- valgrind
os:
  - linux
language: cpp

install:
  #from: https://github.com/boostorg/hana/blob/master/.travis.yml
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.25/cmake-3.25.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version
  
compiler:
  - gcc

sudo: required
script:
  ## Link gcc-5 and g++-5 to their standard commands
  #- ln -s /usr/bin/gcc-5 /usr/local/bin/gcc
  #- ln -s /usr/bin/g++-5 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Go to the travis build dir
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build || true
  - cd build/
  - cmake -DBUILD_EXAMPLES=ON -DBUILD_GMOCK=ON -DBUILD_IMPORT_EXPORT=ON -DBUILD_TESTING=ON -DBUILD_TESTS=ON ..
  - make
notifications:
  email: false
